compilers=&nvcc:&clang:&clang_hip
defaultCompiler=nvcc-default
supportsBinary=true
supportsExecute=false
demangler=/usr/local/cuda/bin/cu++filt
objdumper=/usr/local/cuda/bin/cuobjdump

group.nvcc.compilers=nvcc-default
group.nvcc.options=--keep-device-functions
group.nvcc.versionRe=^.*
group.nvcc.compilerType=nvcc
group.nvcc.nvdisasm=/usr/local/cuda/bin/nvdisasm

compiler.nvcc-default.name=NVCC system
compiler.nvcc-default.includeFlag=-I
compiler.nvcc-default.exe=/usr/local/cuda/bin/nvcc
compiler.nvcc-default.alias=nvcc

group.clang.compilers=cltrunkdef
group.clang.options=--cuda-path=/usr/local/cuda --cuda-gpu-arch=sm_61 --cuda-device-only 
group.clang.compilerType=clang-cuda
group.clang.nvdisasm=/usr/local/cuda/bin/nvdisasm

compiler.cltrunkdef.name=clang trunk
compiler.cltrunkdef.exe=/usr/bin/clang++
compiler.cltrunkdef.alias=cltrunk

group.clang_hip.compilers=hiptrunkdef
group.clang_hip.options=-x hip --offload-arch=gfx908 --cuda-device-only -nocudainc -nocudalib -include __clang_hip_runtime_wrapper.h
group.clang_hip.compilerType=clang-hip
group.clang_hip.objdumperType=llvm
group.clang_hip.rpathFlag=-L

compiler.hiptrunkdef.name=clang/HIP(w/o HIP SDK)
compiler.hiptrunkdef.exe=/usr/bin/clang++
compiler.hiptrunkdef.objdumper=/usr/bin/llvm-objdump
compiler.hiptrunkdef.alias=hiptrunk

#group.ptxas.instructionSet=ptx
#group.nvcc121.nvdisasm.instructionSet=ptx

#group.nvcc121.instructionSet=ptx
#instructionSet=ptx
#supportsAsmDocs=true

libs=dpdk

libs.dpdk.name=DPDK
libs.dpdk.url=https://github.com/DPDK/dpdk

libs.dpdk.versions=main
libs.dpdk.versions.main.version=GitHub Main

# Must install dpdk first using Meson & ninja to
# get this flat lib directory (i.e., /usr/local/include)
# (see installation docs)
libs.dpdk.versions.main.path=/usr/local/include
